imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect:    false

doctrine:
    dbal:
        default_connection: test

stof_doctrine_extensions:
    orm:
        test:
            timestampable: true

swiftmailer:
    disable_delivery: true

web_profiler:
    toolbar:             false
    intercept_redirects: false
