# DunglasJsonLdBundle
api_doc:
    resource: @DunglasJsonLdApiBundle/Resources/config/routing.xml
api:
    resource: .
    type:     json-ld
    prefix:   /api

# FOSUserBundle
fos_user:
    resource: @FOSUserBundle/Resources/config/routing/all.xml

# NelmioApiDocBundle
NelmioApiDocBundle:
    resource: @NelmioApiDocBundle/Resources/config/routing.yml
    prefix:   /api-doc
