# DunglasJsonLdBundle
api:
    resource: .
    type:     api
    prefix:   /api

#login:
#    resource: @ApiUserBundle/Controller/SecurityController.php
#    type:     annotation

# FOSUserBundle
fos_user_security_login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:     /api/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

front:
    resource: @FrontBundle/Controller
    type:     annotation

# NelmioApiDocBundle
NelmioApiDocBundle:
    resource: @NelmioApiDocBundle/Resources/config/routing.yml
    prefix:   /api-doc
