parameters:
#    parameter_name: value

services:

    #
    # Resources
    #
    resource.user:
        parent:    api.resource
        arguments: [ ApiBundle\Bundles\UserBundle\Entity\User ]
        calls:
            - [ initNormalizationContext, [ { groups: [ user ] } ] ]
            - [ initDenormalizationContext, [ { groups: [ user ] } ] ]
        tags:      [ { name: api.resource } ]
