mgate_publi_publiposter:
    pattern: /documents/telecharger/etude/{id_etude}/{doc}/{key}
    defaults: {_controller: mgatePubliBundle:Traitement:publiposterEtude, key : -1}
    requirements:
        id_etude:  \d+
        key: \d+
        doc: AP|CC|FA|RM|PVR|PVI|FS|DM|FI|BV
        #change tolower
    
mgate_publi_telecharger:
    pattern: /publi/publiposter/telecharger
    defaults: {_controller: mgatePubliBundle:Traitement:telecharger}
    


mgate_publi_publiposter_eleve:
    pattern: /documents/telecharger/eleve/{id_eleve}/{doc}/{key}
    defaults: {_controller: mgatePubliBundle:Traitement:publiposterEleve, key : -1}
    requirements:
        id_eleve:  \d+
        key: \d+
        doc: AC|AA|CE
        
        
######################
# UPLOAD DE DOCUMENT #
######################
mgate_publi_documenttype_index:
    pattern: /Documents
    defaults: {_controller: mgatePubliBundle:Document:index}

mgate_publi_document_uploadEtude:
    pattern: /Documents/Upload/Etude/{numero}
    defaults: {_controller: mgatePubliBundle:Document:uploadEtude}
    requirements:
        numero:  \d+
        
mgate_publi_document_uploadEtudiant:
    pattern: /Documents/Upload/Etudiant/{id}
    defaults: {_controller: mgatePubliBundle:Document:uploadEtudiant}
    requirements:
        id:  \d+

mgate_publi_document_uploadFormation:
    pattern: /Documents/Upload/Formation/{id}
    defaults: {_controller: mgatePubliBundle:Document:uploadFormation}
    requirements:
        id:  \d+
        
mgate_publi_document_uploadDoctype:
    pattern: /Documents/Upload/Doctype
    defaults: {_controller: mgatePubliBundle:Document:uploadDoctype}

mgate_publi_document_delete:
    pattern: /Documents/Supprimer/{id}
    defaults: {_controller: mgatePubliBundle:Document:delete}
    requirements:
        id:  \d+
  