parameters:
#    mgate_publi.example.class: mgate\PubliBundle\Example
    mgate.conversionlettre.class: mgate\PubliBundle\Controller\ConversionLettreController
    mgate.twigextentionmanager.class: mgate\PubliBundle\Manager\TwigExtensionManager


services:
    mgate.conversionlettre:
        class: "%mgate.conversionlettre.class%"
    twig.stringloader:
        class: Twig_Loader_String
        tags:
            - { name: twig.loader }
    mgate.twig_extension:
        class: "%mgate.twigextentionmanager.class%"
        tags:
            - { name: twig.extension }



#services:
#    mgate_publi.example:
#        class: %mgate_publi.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]