services:
    api.user.roles:
        class:     ApiBundle\Utils\UserRoles
        arguments: [ %security.role_hierarchy.roles% ]


    # Native filters
    api.filter.order_filter:
        parent: loopback_api.filter.order_filter

    api.filter.where_filter:
        parent: loopback_api.filter.where_filter


    #
    # Resources exposed to the API
    #
    # Job resource
    resource.job:
        parent:    api.resource
        arguments: [ ApiBundle\Entity\Job ]
        calls:
            - method:    initFilters
              arguments:
                -
                    -    @api.filter.order_filter
                    -    @api.filter.where_filter
            - method:    initNormalizationContext
              arguments: [ { groups: [ job, user ] } ]
        tags:      [ { name: api.resource } ]


    # Mandate resource
    resource.mandate:
        parent:    api.resource
        arguments: [ ApiBundle\Entity\Mandate ]
        calls:
            - method:    initFilters
              arguments:
                -
                    -    @api.filter.order_filter
                    -    @api.filter.where_filter
        tags:      [ { name: api.resource } ]


    # User resource
    resource.user:
        parent:    api.resource
        arguments: [ ApiBundle\Entity\User ]
        calls:
            - method:    initFilters
              arguments:
                -
                    -    @api.filter.order_filter
                    -    @api.filter.where_filter
            - method:    initNormalizationContext
              arguments: [ { groups: [ user ] } ]
        tags:      [ { name: api.resource } ]
