parameters:
    api_user.user_roles.class: ApiBundle\Utils\UserRoles

services:

    api.user.roles:
        class:     %api_user.user_roles.class%
        arguments: [ %security.role_hierarchy.roles% ]

    #
    # Native Filters
    #
    api.dunglas_filter.where_filter:
        parent:   api.doctrine.orm.search_filter
        class:    ApiBundle\Filter\WhereFilter
        abstract: true
        public:   false
        calls:
            - method:    initParameter
              arguments: [ where ]

    api.dunglas_filter.order_filter:
        parent:   api.doctrine.orm.order_filter
        class:    ApiBundle\Filter\OrderFilter
        abstract: true
        public:   false
        calls:
            - method:    initParameter
              arguments: [ order ]

    api.filter.where_filter:
        parent:   api.dunglas_filter.where_filter
        class:    ApiBundle\Filter\WhereFilter
        public:   false

    api.filter.order_filter:
        parent:   api.dunglas_filter.order_filter
        class:    ApiBundle\Filter\OrderFilter
        public:   false


    #
    # Resources exposed to the API
    #
    api.app_resource:
        parent:   api.resource
        abstract: true
        public:   false
        calls:
            - method:    addFilter
              arguments: [ @api.filter.where_filter ]
            - method:    addFilter
              arguments: [ @api.filter.order_filter ]

    resource.job:
        parent:    api.app_resource
        arguments: [ ApiBundle\Entity\Job ]
        calls:
            - method:    initNormalizationContext
              arguments: [ { groups: [ job, user ] } ]
        tags:      [ { name: api.resource } ]

    resource.mandate:
        parent:    api.app_resource
        arguments: [ ApiBundle\Entity\Mandate ]
        tags:      [ { name: api.resource } ]

    resource.user.where_filter:
        parent:    api.dunglas_filter.where_filter
        arguments: [ [ 'id', 'username', 'fullname', 'email', 'roles' ] ]

    resource.user.order_filter:
        parent:    api.dunglas_filter.order_filter
        arguments: [ [ 'id', 'username', 'fullname', 'email', 'roles' ] ]

    resource.user:
        parent:    api.resource
        arguments: [ ApiBundle\Entity\User ]
        calls:
            - method:    initNormalizationContext
              arguments: [ { groups: [ user ] } ]
            - method:    addFilter
              arguments: [ @resource.user.where_filter ]
            - method:    addFilter
              arguments: [ @resource.user.order_filter ]
        tags:      [ { name: api.resource } ]
