parameters:
    api_user.user_roles.class: ApiBundle\Utils\UserRoles

services:

    api.user.roles:
        class:     %api_user.user_roles.class%
        arguments: [ %security.role_hierarchy.roles% ]

    #
    # Resources exposed to the API
    #
    resource.job.search_filter

    resource.job:
        parent:    api.resource
        arguments: [ ApiBundle\Entity\Job ]
        calls:
            - method:    initNormalizationContext
              arguments: [ { groups: [ job, user ] } ]
        tags:      [ { name: api.resource } ]

    resource.mandate:
        parent:    api.resource
        arguments: [ ApiBundle\Entity\Mandate ]
        tags:      [ { name: api.resource } ]

    resource.user:
        parent:    api.resource
        arguments: [ ApiBundle\Entity\User ]
        calls:
            - method:    initNormalizationContext
              arguments: [ { groups: [ user ] } ]
        tags:      [ { name: api.resource } ]
