parameters:
    api_user.user_roles.class: ApiBundle\Bundle\UserBundle\Utils\UserRoles

services:
    api.user.roles:
        class:     %api_user.user_roles.class%
        arguments: [ %security.role_hierarchy.roles% ]
